export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const ADDTODO = "ADDTODO"
export const REMOVETODO = "REMOVETODO"
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER"
export const TOGGLE_TODO = "TOGGLE_TODO"
export const VisibilityFilters = {
  SHOW_ALL: "SHOW_ALL",
  SHOW_COMPLETED: "SHOW_COMPLETED",
  SHOW_ACTIVE: "SHOW_ACTIVE"
}
